spring:
  jpa:
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/victor_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    schemas: public
    enabled: true
    locations: classpath:db/migration
  minio:
    url: http://127.0.0.1:9000
    bucket: victor-bucket
    access-key: jovCVgoYDWbK9zjQ
    secret-key: zyx3ZUOI3DGCMJDhk65kCirANvAmcB2I