create table meta_documents
(
    id bigint generated by default as identity,
    file_name character varying(255),
    file_size bigint,
    file_original_name character varying(255),
    content_type character varying(255),
    constraint meta_documents_pkey primary key (id)
);

create table products
(
    id bigint generated by default as identity,
    name character varying(255),
    description character varying(255),
    amount smallint,
    price bigint,
    photo_id int,
    constraint products_pkey PRIMARY KEY(id),
    CONSTRAINT meta_documents_fkey FOREIGN KEY(photo_id) references meta_documents(id)
);